---
stages:
- name: TEST
  inputs:
  - type: git
    branch: master
    service: ${CONTROLLER_REPO}
  triggers:
  - type: commit
  properties:
  - name: LOGISTICS_WIZARD_ENV
    value: TEST
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: SMTP_SERVER
    value: smtp.gmail.com
    type: text
  - name: SMTP_SERVER_PORT
    value: 587
    type: text
  - name: ERP_SERVICE
    value: http://0.0.0.0:3000
    type: text
  - name: TEST_SMTP_USER_NAME
    value: ${TEST_SMTP_USER_NAME}
    type: secure
  - name: TEST_SMTP_PASSWORD
    value: ${TEST_SMTP_PASSWORD}
    type: secure
  jobs:
  - name: Unit Test
    type: tester
    script: |
      #!/bin/bash
      # Get ERP module
      git submodule init
      git submodule update
      cd modules/erp
      # Download Node v4.4
      npm config delete prefix
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
      . ~/.nvm/nvm.sh
      nvm install 4.4
      # Install ERP dependencies and run app in background
      npm install
      nohup bash -c "npm start" &
      # Export email env vars
      cd ../..
      export SMTP_USER_NAME=${TEST_SMTP_USER_NAME}
      export SMTP_PASSWORD=${TEST_SMTP_PASSWORD}
      # Download Python dependencies
      sudo pip install virtualenv
      virtualenv venv
      source venv/bin/activate
      export PYTHONPATH=$PWD
      pip install -r requirements.dev.txt
      # Run unit and coverage tests
      coverage run server/tests/run_tests.py
      if [ -z ${COVERALLS_REPO_TOKEN} ]; then
        echo No Coveralls token specified, skipping coveralls.io upload
      else
        COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
      fi
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${CONTROLLER_REPO}
  triggers:
  - type: stage
  jobs:
  - name: Build
    type: builder
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: LOGISTICS_WIZARD_ENV
    value: PROD
    type: text
  - name: SMTP_SERVER
    value: smtp.gmail.com
    type: text
  - name: SMTP_SERVER_PORT
    value: 587
    type: text
  - name: PROD_SMTP_USER_NAME
    value: ${PROD_SMTP_USER_NAME}
    type: secure
  - name: PROD_SMTP_PASSWORD
    value: ${PROD_SMTP_PASSWORD}
    type: secure
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Deploy app
      if ! cf app $CF_APP; then
        cf push $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP
        cf delete $OLD_CF_APP -f
      fi
      # Set app's env vars
      cf set-env ${CF_APP_NAME} LOGISTICS_WIZARD_ENV ${LOGISTICS_WIZARD_ENV}
      cf set-env ${CF_APP_NAME} SMTP_SERVER ${SMTP_SERVER}
      cf set-env ${CF_APP_NAME} SMTP_SERVER_PORT ${SMTP_SERVER_PORT}
      cf set-env ${CF_APP_NAME} SMTP_USER_NAME ${PROD_SMTP_USER_NAME}
      cf set-env ${CF_APP_NAME} SMTP_PASSWORD ${PROD_SMTP_PASSWORD}
      cf restage ${CF_APP_NAME}
