---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
  properties:
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
- name: TEST (In Memory)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Unit Test
    type: tester
    test_type: simple
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST.sh

      # devops insights test record upload in 'pipeline-TEST.sh' see npm script 'idra' for details
      
    coverage_type: istanbul
    coverage_directory: ./coverage/lcov-report
    coverage_file_pattern: ./coverage/coverage.json
  - name: Quality Gate
    type: tester
    extension_id: ibm.devops.services.pipeline.dra_devops_gate
    CRITERIA: ERP Quality Policy
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh

      # begin devops insights

      # install devops CLI
      export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      npm install -g grunt-idra3

      # set env vars
      export DEPLOYABLE_ID=$(bx app env $CF_APP_NAME | grep application_id | awk '{ print $2 }' | cut -c 2-37)
      export STATUS=$(bx app show $CF_APP_NAME | tail -1 | awk '{ print $2 }')
      if [ "$STATUS" = "running" ]; then
        export STATUS=pass
      else
        export STATUS=fail
      fi

      # upload deployment record
      idra --publishdeployrecord  --env=$LOGICAL_ENV_NAME --status=pass --deployableid=$DEPLOYABLE_ID

      # end devops insights
- name: TEST (DBaaS)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Unit Test
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST-REAL-DB.sh
