---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
  properties:
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
- name: TEST (In Memory)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  jobs:
  - name: Unit Test
    type: tester
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST.sh
  - name: Quality Gate
    type: tester
    extension_id: ibm.devops.services.pipeline.dra_devops_gate
    CRITERIA: ERP Quality Policy
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh
    properties:
    - name: LOGICAL_ENVIRONMENT_NAME
      value: ${SPACE_NAME}
- name: TEST (DBaaS)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Unit Test
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST-REAL-DB.sh
