---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: dev
    service: ${ERP_API_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
- name: TEST
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: LOGISTICS_WIZARD_ENV
    value: TEST
    type: text
  jobs:
  - name: Unit Test
    type: tester
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST.sh
- name: TEST (PostgreSQL)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Unit Test
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST-REAL-DB.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: LOGISTICS_WIZARD_ENV
    value: DEV
    type: text
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh
