---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
  properties:
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
- name: TEST (In Memory)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Unit Test
    type: tester
    test_type: simple
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST.sh      
    coverage_type: istanbul
    coverage_directory: ./coverage/lcov-report
    coverage_file_pattern: ./coverage/coverage.json
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  - name: IBM_CLOUD_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  - name: CLOUDANT_SERVICE_PLAN
    value: Lite
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${IAM_API_KEY}
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v6.7.0/bin:$PATH

      ./.bluemix/pipeline-DEPLOY.sh
- name: TEST (DBaaS)
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  jobs:
  - name: Unit Test
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${IAM_API_KEY}
    script: |
      #!/bin/bash
      ./.bluemix/pipeline-TEST-REAL-DB.sh
