---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: dev
    service: ${RECOMMENDATION_REPO}
  triggers:
  - type: commit
  properties:
  - name: LOGISTICS_WIZARD_ENV
    value: DEV
    type: text
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-BUILD.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: LOGISTICS_WIZARD_ENV
    value: DEV
    type: text
  - name: PACKAGE_NAME
    value: dev-logistics-wizard-recommendation
    type: text
  - name: CLOUDANT_DATABASE
    value: dev-recommendations
    type: text
  - name: OPENWHISK_AUTH
    value: ${OPENWHISK_AUTH}
    type: secure
  - name: CONTROLLER_SERVICE_APP_NAME
    value: ${CONTROLLER_SERVICE_APP_NAME}
    type: text
  - name: REGION_ID
    value: ${REGION_ID}
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: "not-used"
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh
