---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: COVERALLS_SERVICE_NAME
    value: bluemix-devops-services
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${PACKAGE_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-BUILD.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: REPO_BRANCH
    value: ${REPO_BRANCH}
  - name: PACKAGE_NAME
    value: ${PACKAGE_NAME}
    type: text
  - name: CLOUDANT_DATABASE
    value: ${CLOUDANT_DATABASE}
    type: text
  - name: CONTROLLER_SERVICE_APP_NAME
    value: ${CONTROLLER_SERVICE_APP_NAME}
    type: text
  - name: REGION_ID
    value: ${REGION_ID}
  - name: IAM_API_KEY
    value: ${IAM_API_KEY}
    type: secure
  - name: LOGICAL_APP_NAME
    value: ${PACKAGE_NAME}
    type: text
  - name: BUILD_PREFIX
    value: ${REPO_BRANCH}
    type: text
  - name: LOGICAL_ENV_NAME
    value: ${SPACE_NAME}
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: "not-used"
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-DEPLOY.sh

      # begin devops insights

      # install devops CLI
      export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      npm install -g grunt-idra3

      # set env vars
      export DEPLOYABLE_ID=$PACKAGE_NAME
      export NUM_ACTIONS=$(bx cloud-functions action list $PACKAGE_NAME | wc -l)

      echo $NUM_ACTIONS actions were deployed in package $PACKAGE_NAME

      if [ "$NUM_ACTIONS" = "5" ]; then
        export STATUS=pass
      else
        export STATUS=fail
      fi

      # upload deployment record
      idra --publishdeployrecord  --env=$LOGICAL_ENV_NAME --status=pass --deployableid=$DEPLOYABLE_ID

      # end devops insights
