---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${WEBUI_REPO}
  triggers:
  - type: commit
  properties:
  - name: PROD_CONTROLLER_SERVICE
    value: ${PROD_CONTROLLER_SERVICE}
    type: text
  - name: COVERALLS_REPO_TOKEN
    value: ${COVERALLS_REPO_TOKEN}
    type: secure
  jobs:
  - name: Build
    type: builder
    artifact_dir: dist
    build_type: shell
    script: |-
      #!/bin/bash
      npm config delete prefix
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
      . ~/.nvm/nvm.sh
      nvm install 4.4
      npm install
      npm run test
      npm run check-coverage
      if [ -z ${COVERALLS_REPO_TOKEN} ]; then
        echo No Coveralls token specified, skipping coveralls.io upload
      else
        COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN npm run coveralls
      fi
      # inject the location of the controller service
      export CONTROLLER_SERVICE=${PROD_CONTROLLER_SERVICE}
      npm run deploy:prod
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    application: ${PROD_CF_APP_NAME}
    type: text
  - name: LOGISTICS_WIZARD_ENV
    value: PROD
    type: text
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${PROD_CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Push
      if ! cf app $CF_APP; then
        cf push $CF_APP -n $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP -n $CF_APP
        cf delete $OLD_CF_APP -f
      fi
      # Set app's env vars
      cf set-env $CF_APP LOGISTICS_WIZARD_ENV ${LOGISTICS_WIZARD_ENV}
      cf restage $CF_APP
