---
stages:
- name: DEV-BUILD
  inputs:
  - type: git
    branch: dev
    service: ${WEBUI_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      npm config delete prefix
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
      . ~/.nvm/nvm.sh
      nvm install 4.4
      npm install
      npm run test
      npm run deploy:prod
- name: DEV-DEPLOY
  inputs:
  - type: job
    stage: DEV-BUILD
    job: Build
  properties:
  - name: CF_APP_NAME
    value: ${DEV_CF_APP_NAME}
    type: text
  - name: LOGISTICS_WIZARD_ENV
    value: DEV
    type: text
  jobs:
  - name: Deploy to dev
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${DEV_CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Push the app
      cf push "${CF_APP_NAME}" -n $CF_APP --no-start

      # Set app's env vars
      cf set-env ${CF_APP_NAME} LOGISTICS_WIZARD_ENV ${LOGISTICS_WIZARD_ENV}
      cf start ${CF_APP}    
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${WEBUI_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      npm config delete prefix
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.2/install.sh | bash
      . ~/.nvm/nvm.sh
      nvm install 4.4
      npm install
      npm run test
      npm run deploy:prod
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    application: ${PROD_CF_APP_NAME}
    type: text
  - name: LOGISTICS_WIZARD_ENV
    value: PROD
    type: text
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${PROD_CF_APP_NAME}
    script: |-
      #!/bin/bash
      # Push
      if ! cf app $CF_APP; then
        cf push $CF_APP -n $CF_APP
      else
        OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
        rollback() {
          set +e
          if cf app $OLD_CF_APP; then
            cf logs $CF_APP --recent
            cf delete $CF_APP -f
            cf rename $OLD_CF_APP $CF_APP
          fi
          exit 1
        }
        set -e
        trap rollback ERR
        cf rename $CF_APP $OLD_CF_APP
        cf push $CF_APP -n $CF_APP
        cf delete $OLD_CF_APP -f
      fi
      # Set app's env vars
      cf set-env $CF_APP LOGISTICS_WIZARD_ENV ${LOGISTICS_WIZARD_ENV}
      cf restage $CF_APP
